version: "3"
services:
  nginx:
    build: ./docker/nginx
    container_name: "tp6_nginx"
    restart: always
    ports:
      - "8082:80"
    links:
      - "php74"
    volumes:
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d
  php74:
    build: ./docker/php
    container_name: "tp6_p74"
    restart: always
    ports:
      - "9002:9000"
    volumes:
      - ./:/www/tp
  mysql_compose:
    image: mysql:5.7
    container_name: "tp6_mysql5.7"
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "654321"
      MYSQL_USER: "tp_demo"
      MYSQL_PASSWORD: "tp_demo"
      MYSQL_DATABASE: "tp_demo"
  redis:
    image: redis:6.0.6
    container_name: "tp6-redis"
    restart: always
    ports:
      - "16379:6379"